### ISSUE TITLE
Plugin path error

### ISSUE THREAD

**Issue by joopvanduin** [trentrichardson/cakephp-shrink#11]
Hi

Tried to use this plugin but it can not load for example a css file from a plugin webrott/css folder.

I debugged it and found the problem in Shrink.php

$plugin_path = preg_replace('/(\/+|\\+)/', DS, APP . DS . 'plugins' . DS . $plugin . DS . 'webroot' .DS. $plugin_rel_path);

APP = /src
plugins are in /plugins (same level as src in CakePhph 3)

So APP . 'plugins' = /src/plugins it should be /plugins

All  the best
Joop van Duin

**Comment by trentrichardson** [comment]
Sorry for the delay on this. I appreciate you reporting the fix. I've committed a fix and published a new version
