### ISSUE TITLE
Plugin isn't Minify .js files in CakePHP 3.0.3

### ISSUE THREAD

**Issue by ghost** [trentrichardson/cakephp-shrink#5]
I am using your plugin "Shrink CakePHP Plugin" but the plugin this unifying and minifying the .css files but not minifying the .js files (though this unifying all .js files), what the reason for this behavior and how to prevent this behavior?

How I'm using:

In my home.ctp (inside head tags):

<?= $this->Shrink->css(['Bootstrap/css/bootstrap.min.css',
            'font-awesome-4.3.0/css/font-awesome.min.css', 'datepicker/css/datepicker.css',
            'jquery-bxslider/jquery.bxslider.css', 'style.css', 'menu-plugin.css']) ?>
        <?= $this->Shrink->js(['jquery-1.11.1.min.js', 'bootstrap.min.js',
            'Jquery-Validate/jquery.validate.min.js', 'datepicker/js/bootstrap-datepicker.js',
            'jquery-bxslider/jquery.bxslider.min.js', 'main.js']) ?>
        <?= $this->Shrink->fetch('css') ?>
        <?= $this->Shrink->fetch('js') ?>

In AppController.php (inside initialize() method) I add this line:

$this->helpers[] = 'Shrink.Shrink';

**Comment by danielignatius** [comment]
I tried that as well. I can confirm that the plugin isn't minify the .js files.

**Comment by riddlemd** [comment]
If anyone needs this fixed changed open Shrink.php and edit line 70 from `if($cakedebug >= $this->settings['debugLevel']){` to `if($cakedebug){` -- and in your helper settings the debugLevel now works like this: 0 = compressed, no debug, 1 = compressed with debug, 2 = no compression with debug.

**Comment by trentrichardson** [comment]
Thanks for posting the fix. After Christmas I will try to get this project
up to speed.

**Comment by riddlemd** [comment]
I've forked the project, feel free to pull my changes back in (sans composer file and readme)

**Comment by trentrichardson** [comment]
@riddlemd Thank you for posting your fixes. They are now in the cakephp-v3.0 branch. I'll try to do a good look over, run tests, and try to go ahead and get it merged to master.
