### ISSUE TITLE
About Contributions

### ISSUE THREAD

**Issue by clthck** [trentrichardson/cakephp-shrink#6]
Hi Trent

I'd like to contribute to this repo. How can I do that? I don't see any contribution guides on readme.md

Regards,
clthck

**Comment by trentrichardson** [comment]
Hey @clthck 

The quick rundown is that the two branches cakephp-v2.0 and cakephp-v3.0 are the two dev branches for the given version of cakephp you are developing towards.  Make your changes to these branches and send back the pull request.  I generally will review the changes and merge the cakephp-v3.0 branch to the master branch when it is ready.

Please try to write tests for any work you do if possible.  To run the tests you will need to setup some node/npm packages to run less, coffee, typescript, etc. and also setup the the composer packages.  You might look in the travis.yml to get a quick rundown of what is needed to be installed:

https://github.com/trentrichardson/cakephp-shrink/blob/master/.travis.yml

then just run `phpunit` in the project directory.  Depending on how you have phpunit installed you may need to call it in `./vendor/bin/phpunit`

Hope that helps, and thanks for any help!

**Comment by clthck** [comment]
If I make changes to those branches and send back the pull request, does that reflect on my github profile's activity graph?
Well, to be honest, I'm going to start building my github profile with this repository.

**Comment by trentrichardson** [comment]
I'm not sure to be honest on how github populates the activity graph..
